### ISSUE TITLE
Binding poses and lipid occupancy

### ISSUE THREAD

**Issue by poojari1** [wlsong/PyLipID#6]
Dear Wanling,

I have couple of questions on the PyLipID ouput.

1) Binding poses:
Inside the "Binding_Poses" folder I see that the tool writes out binding site PDB files and the number of binding sites corresponds to the "BindingSites_Info_PAPC.txt" file.  Please find attached the "BindingSites_Info_PAPC.txt" file.

According to the  "BindingSites_Info_PAPC.txt" file, Binding site 1 shows "BS Lipid Occupancy:     94.941 %". So I went inside 
"Binding_Poses" folder and looked into the 10 poses under "BSid1_No*.pdb" using VMD and also marked all the residues listed  in "# Binding site 1". But, I dont see any lipids bound at the binding site residues, the lipids from each of the 10 poses are away from the binding site 1. 

Please can i know if this if the correct way to check for lipid bounds at the binding site listed in the "BindingSites_Info_PAPC.txt" file?    

2) Lipid Occupancy: 
For each binding site there is BS Lipid Occupancy printed in the header, followed by lipid occupancy per residue in the 6th column.  I was expecting that the  BS Lipid Occupancy printed in the header is the average value coming from the  binding site residues. However, it does not seem so. For example in the attached "BindingSites_Info_PAPC.txt" file for "Binding Site 11" it shows BS Lipid Occupancy:      3.159 %, but the 3 residues have occupancy of 60.6%, 48.5% and 2.6%. 

Please can you also clarify this.

[BindingSites_Info_PAPC.txt](https://github.com/wlsong/PyLipID/files/5174123/BindingSites_Info_PAPC.txt)

Kind Regards,
Chetan

**Comment by wlsong** [comment]
Hi Chetan, 

Thanks for reporting the issues :)
-- Binding poses: yes, it was an issue that I noticed last week which resulted from a typo in the script and had led to wrong binding poses being generated. Sorry for this error. I've corrected it in the latest version. 
-- BS occupancy: BS occupancy is not the average of occupancies of the comprising residues. BS occupancy is calculated as the percentage of frames in which the binding site is occupied by the specified lipids. I was using a more stringent rule for BS occupancy calculation which had led to the inconsistency you saw from your results. I think you raised a good point that this inconsistency could be confusing and misleading, so that now I've changed the script such that the rules for defining residue occupancy and binding site occupancy are the same. Please give it a go the latest version and let me know how it goes. Thanks!

Wanling

**Comment by poojari1** [comment]
Dear Wanling,

Thanks for the fixes. 

-The binding poses are working correctly now. 

-If I understand correctly, the definition for BS Lipid Occupancy printed for each binding site and those listed for each residue are the same now, i.e.  percentage of frames in which the residue is occupied by the specified lipids.

-I have another question regarding the Duration and Residence time printed for each binding site and for each residue. 
In the   "BindingSites_Info_*.txt" file the definition is printed as:
# Duration/Residence Time: average length of a continuous interaction of lipid with the given residue (in unit of ns);

I went through the Methods section of your article  in Structure27, 392–403.e1–e3, February 5, 2019 for the definition of Duration and residence time. As I understand from the paper, on choosing a dual cut-off of 0.55 and 1.0 nm for analysis,  if a lipid is within 0.55nm where there is continuous interaction with the protein then it is considered as residence time and if the lipid lies within 0.55nm and 1.0 nm cutoff it will be referred to a lipid-interaction duration time. Please can I know if my understanding here is correct. 


Kind Regards,
Chetan
